### ISSUE TITLE
Rule: project name in pom must be readable version of artifcat id

### ISSUE THREAD

**Issue by jakobbraun** [exasol/project-keeper#124]
Idea:
pom.name  = pom.artifac_id.replace("_", " ").capitalizeWords()

**Comment by redcatbear** [comment]
It's not always this easy:

| Machine readable ID        | Human readable name        |
|----------------------------|----------------------------|
| virtual-schema-common-java | Virtual Schema Common Java |
| row-level-security         | Row-level Security         |

**Comment by jakobbraun** [comment]
ok, then I'd not add it since it can't be fixed automatically.
