### ISSUE TITLE
Self update

### ISSUE THREAD

**Issue by jakobbraun** [exasol/project-keeper#140]
Add a feature to project keeper to update itself to the latest available version.

**Comment by ckunki** [comment]
This will probably require an additional dependency to 
```
<dependency>
    <groupId>org.kohsuke</groupId>
    <artifactId>github-api</artifactId>
    <version>1.307</version>
</dependency>
```

**Comment by ckunki** [comment]
The last comment was based on wrong assumptions -- please ignore.
