### ISSUE TITLE
Template update: dependency update check

### ISSUE THREAD

**Issue by jakobbraun** [exasol/project-keeper#160]
Maven plugin `versions-maven-plugin` included in file `pk_generated_parent.pom` reports if newer versions are available for some of the projects dependencies. This report is by default displayed for each run of maven package. 

The current ticket proposes to remove this report and to replace it by a separate git hub action.

**Comment by ckunki** [comment]
Grooming with @kaklakariada: Closing ticket due to estimated implementation effort appears to outweigh the expected benefit.
