### ISSUE TITLE
Allow-list for badges in README

### ISSUE THREAD

**Issue by redcatbear** [exasol/project-keeper#167]
## Situation

Non-Java projects need different badges than the standard set PK 0.10.0 requires.
Users should be able to tell PK, which of the badges make sense in a given project. If a include-list exists, PK should only complain about missing badges in the include-list.

## Acceptance Criteria

* Users can specify and include-list for badge names (e.g. `Quality Gate Status`).
* If a include-list for badges exists, PK only mandates the existence of the listed badges in the README.
* PK ignores additional non-standard badges.

**Comment by morazow** [comment]
I have faced similar issue.

Sometimes for maven badge artifact name can be different than the one defined in the `pom.xml` file, for example when doing cross releasing. As a workaround, I had exclude whole readme file.

Adding an badges include (or exclude) list would be helpful.

**Comment by ckunki** [comment]
Grooming with @kaklakariada:
PK uses a dedicated finding "E-PK-CORE-62" for badges.
In case of a non-standard badges used by a project users can simply add an exclude to their file `.project-keeper.yml`:
```
excludes:
  - "(?s)E-PK-CORE-62: The project's README.md does not contain a valid badges block.*"
```
Note: prefix (?s) is only required for PK versions before 2.7.0.
See
