### ISSUE TITLE
Run release-droid-validation on each PR

### ISSUE THREAD

**Issue by jakobbraun** [exasol/project-keeper#207]
Scenario A
1. Developer implements a ticket and creates a pull request 
2. done 

Scenario B 
1. (identical to scenario A)
2. After successful build, review and merge the developer might want to run release-droid to create a new release 
3. If release-droid reports problems then the developer needs to create another branch and PR and repeat the procedure 

The current ticket therefore proposes to add a github action that runs release droid validation for each PR in advance to find potential release problems as soon as possible and to enable the developer to fix these issues on the current already existing branch and PR. 

For scenario A the github action should not make the build fail but report the findings only as an optional comment on the PR.

**Comment by kaklakariada** [comment]
This was closed by accident, it's not yet implemented.

**Comment by ckunki** [comment]
Grooming with @kaklakariada: Implementation effort seems to outweigh the expected benefits. 
Workaround:  If the developer plans to make a release, then the developer could also run release-droid validation manually.
Scenario B is accepted.
