### ISSUE TITLE
Make schedule dynamic in .github/workflows/dependencies_check.yml

### ISSUE THREAD

**Issue by jakobbraun** [exasol/project-keeper#22]
Required to distribute load on gihub actions

**Comment by kaklakariada** [comment]
The [scheduling of GitHub Actions](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) only allows specifying cron expressions, not `@daily` or similar. A possible solution would be to calculate a hash based on the repository name and based on this hash determine hour and minute for the scheduling.

But as we don't have issues with this at the moment I will close this ticket.
