### ISSUE TITLE
Add cancelling of Github action in-progress jobs per workflow to CI templates

### ISSUE THREAD

**Issue by morazow** [exasol/project-keeper#242]
```
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
```

https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow

**Comment by jakobbraun** [comment]
what's the goal of this?

**Comment by morazow** [comment]
Using less energy and being more greener.
For example, when doing reviews we have many commits which each runs CI, but it is okay to let the latest one run and cancel all previous already running ones.

**Comment by jakobbraun** [comment]
Oh, that makes sense!
So it's not about canceling the others when one failed, but just making sure that we cancel the old ones once there is a new commit?

**Comment by morazow** [comment]
Yes exactly! 
Mainly from my understanding it cancels in progress runs it is for the same group. So new commit in a PR should cancel in-progress ones and start only one for the last commit only.
