### ISSUE TITLE
Build Javadoc for delomboked code

### ISSUE THREAD

**Issue by jakobbraun** [exasol/project-keeper#278]
Currently, the Javadoc does not contain the classes and methods generated by Lombok.
That's not so cool.
We can generate them by adding `<sourcepath>target/generated-sources/delombok</sourcepath>` to the javadoc plugin's configuration.
However, that will break the build since the generated Javadoc has missing Javadoc tags.

Planned solution:
* Fix in Lombok: https://github.com/projectlombok/lombok/issues/1520
* Activate Javadoc generation for Lombok classes

**Comment by redcatbear** [comment]
We will remove Lombok: #341
