### ISSUE TITLE
Link replacement for JDBC driver license

### ISSUE THREAD

**Issue by redcatbear** [exasol/project-keeper#321]
## Situation

At the moment the JDBC driver's license URL is relative. That means the link points to a file in the project directory, where it should actually point to a URL on the Internet. This causes link checks to break on projects that include the driver.

## Acceptance Criteria

* Local driver license link replace with Internet link

**Comment by kaklakariada** [comment]
Will add the following link replacement by default:
```yaml
linkReplacements:
  - "LICENSE-exasol-jdbc.txt|https://docs.exasol.com/connect_exasol/drivers/jdbc.htm"
```
