### ISSUE TITLE
Update github workflow yml files 

### ISSUE THREAD

**Issue by ckunki** [exasol/project-keeper#329]
`ci-build.yml` is probably ok, while latest run of `release_droid_prepare_original_checksum.yml` failed:
https://github.com/exasol/project-keeper/runs/7408367414?check_suite_focus=true

Suspicion: Probably some changes in `ci-build.yml` need to be migrated to `release_droid_prepare_original_checksum.yml`

**Comment by kaklakariada** [comment]
See branch https://github.com/exasol/project-keeper/compare/bug/329-Update_workflow_yml
