### ISSUE TITLE
Check the pom header 

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/project-keeper#37]
We have different versions of the pom header in different projects.
Need to check it and agree on one.

**Comment by AnastasiiaSergienko** [comment]
Let's use a template from the official documentation:

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

https://maven.apache.org/pom.html

**Comment by redcatbear** [comment]
Not important.
