### ISSUE TITLE
Add support for npm projects

### ISSUE THREAD

**Issue by kaklakariada** [exasol/project-keeper#373]
Some projects use JavaScript/TypeScript with npm as dependency manager, e.g.
* https://github.com/exasol/extension-manager-interface

Open issues
* how to get dependencies? 
  * `npm list --location=project --depth=0 --json`
  * read file `package.json`
  * `npx npm-remote-ls sha@1.2.4`, see https://www.npmjs.com/package/npm-remote-ls
* how to get licenses?  `npx --location=project license-checker --direct --json`
* Where to get the current version of the current project from? Proposal: `package.json`
* Does NPM / TS / JS make a difference between COMPILE, RUNTIME and TEST dependencies?
  * "devDependencies" = TEST or PLUGIN, preferred: PLUGIN
  * "dependencies", see `extension-manager/integrationTesting/extensionForTesting/package.json` = COMPILE 
  * RUNTIME not used for TS / JS

**Comment by ckunki** [comment]
Could you please help me to write down some requirements? 
* Are there files that PK should generate? Do some of these files contain variable parts? Which? 
* Should PK handle dependencies? How?

**Comment by ckunki** [comment]
| File | Description | Proposal for requirements to project-keeper |
|------|------|-------------------------------|
| .gitattributes | | (none) |
| .gitignore | | (none) |
| .npmignore | | (none) |
| jest.config.ts | Configuration for Javascript test framework "Jest" | create initial version from template but accept later manual changes |
| package-lock.json | versions of dependencies, auto-generated during build by developer, fixed for ci-builds | (none) |
| package.json | manually edited dependencies incl. specific versions or version ranges | analyse for dependency report |
| sonar-project.properties | configuration for static code analysis | ? |
| tsconfig.json | Configuration for typescript to javascript compiler | ? |
