### ISSUE TITLE
Fix issues reported by dependabot

### ISSUE THREAD

**Issue by kaklakariada** [exasol/project-keeper#451]
See https://github.com/exasol/project-keeper/security/dependabot

<img width="525" alt="image" src="https://user-images.githubusercontent.com/4711730/235907721-7f10c70e-b558-4711-b99f-7854883eb6f7.png">

**Comment by ckunki** [comment]
Dependabot has detected PK vulnerabilities by looking at a test resource  [project-keeper/src/test/resources/go.mod](https://github.com/exasol/project-keeper/blob/-/project-keeper/src/test/resources/go.mod)

Proposal: reduce the dependencies in this test project or only use dependencies that don’t have vulnerabilities
