### ISSUE TITLE
Support for Lua projects 

### ISSUE THREAD

**Issue by ckunki** [exasol/project-keeper#459]
Generate files
*  `.lua-format`, see for example https://github.com/exasol/exasol-virtual-schema-common-lua/
* `.coverage_config.lua`
  * note exception for foreign libraries, e.g. https://github.com/exasol/exasol-driver-lua

see also #195

### Acceptance Criteria 
1. PK generated the files named above 
2. with appropriate content
3. PK's template for file `.gitattributes` lists these files as "generated".

**Comment by redcatbear** [comment]
Shelved.
