### ISSUE TITLE
Optionally rate artifact-reference-checker:unify check as warning

### ISSUE THREAD

**Issue by ckunki** [exasol/project-keeper#495]
PJ reported a use case in which the developer didn't plan to do a release immediately (for example when updating CI files) but bump the version in the `.pom` file so the current documentation file for the current changes (changelog) doesn't get overwritten.

After that PK forces to update the documentation references to this future version, thus referencing a yet unreleased version.

Problem: References to  a yet unreleased version  might be confusing or wrong towards customers.

Proposed mitigation: Enable PK users to optionally rate `mvn artifact-reference-checker:unify` check as a _warning_ rather than an _error_ condition.

**Comment by kaklakariada** [comment]
This should be implemented in https://github.com/exasol/artifact-reference-checker-maven-plugin/, not in project-keeper. See https://github.com/exasol/artifact-reference-checker-maven-plugin/issues/27
