### ISSUE TITLE
Version of project-keeper in `pom.xml` not in sync with version in `.github/workflows/project-keeper.sh`

### ISSUE THREAD

**Issue by redcatbear** [exasol/project-keeper#501]
## Situation

On the CI server `project-keeper:verify` runs from a shell script under `.github/workflows/project-keeper.sh`. That shell script is automatically installed by project-keeper itself, but it does not seem to get updated.

I had a case where in the `pom.xml` of the project I had:
```xml
    <plugin>
        <groupId>com.exasol</groupId>
        <artifactId>project-keeper-maven-plugin</artifactId>
        <version>2.9.16</version>
        <executions>
            <execution>
                <goals>
                    <goal>verify</goal>
                </goals>
            </execution>
        </executions>
    </plugin>
```

But the shell script had:

```sh
readonly version="2.9.11"
```

This leads to differences in between files generated locally and on the CI server.

## Expected Behavior

Either: PK keeps the version number in that shell script in sync (preferable)
Or: the shell script reads the version from the `pom.xml`

## Actual Behavior

Shell script gets outdated

## Workaround

Update the version in the shell script manually.

## Affected Code

https://github.com/exasol/project-keeper/blob/a0900a3944c4434315d0f7a32f3db89a2e225848/project-keeper/src/main/resources/non_maven_templates/.github/workflows/project-keeper.sh#L8

**Comment by kaklakariada** [comment]
Is there a `pom.xml` in the root dir of the project? If yes, PK will not create or update the mentioned scripts. See source code: https://github.com/exasol/project-keeper/blob/main/project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/FileTemplatesFactory.java#L65
