### ISSUE TITLE
Provide metrics for code quality

### ISSUE THREAD

**Issue by ckunki** [exasol/project-keeper#513]
## Situation

We have a [Maven plugin](https://github.com/exasol/quality-summarizer-maven-plugin/) now that summarizes code quality. At the time of this writing it only extracts coverage, but that is all we need to get started.

PK should make sure that each Java project uses that plugin and runs it during CI

## Acceptance Criteria

* PK adds `quality-summarizer-maven-plugin` to the java projects it is used in.
* PK add the plugin to the CI build

## Blocked
This is blocked by
* https://github.com/exasol/quality-summarizer-maven-plugin/issues/7
* https://github.com/exasol/quality-summarizer-maven-plugin/issues/8
* https://github.com/exasol/quality-summarizer-maven-plugin/issues/9
* https://github.com/exasol/quality-summarizer-maven-plugin/issues/13

**Comment by Nicoretti** [comment]
Maybe this helps: https://sonarcloud.io/web_api/api/measures?deprecated=false

**Comment by kaklakariada** [comment]
After running sonar on a Maven project, it generates a report in `target/sonar/report-task.txt`:

```
organization=exasol
projectKey=com.exasol:project-keeper-root
serverUrl=https://sonarcloud.io
serverVersion=8.0.0.53397
dashboardUrl=https://sonarcloud.io/dashboard?id=com.exasol%3Aproject-keeper-root
ceTaskId=$taskId
ceTaskUrl=https://sonarcloud.io/api/ce/task?id=$taskId
```

When authenticated, the `ceTaskUrl` returns the following content:

```json
{
    "task": {
        "id": "$id",
        "type": "REPORT",
        "componentId": "$id",
        "componentKey": "com.exasol:project-keeper-root",
        "componentName": "Project Keeper Root Project",
        "componentQualifier": "TRK",
        "analysisId": "$id",
        "status": "SUCCESS",
        "submittedAt": "2024-03-21T06:45:20+0100",
        "submitterLogin": "$user@github",
        "startedAt": "2024-03-21T06:45:21+0100",
        "executedAt": "2024-03-21T06:45:24+0100",
        "executionTimeMs": 3795,
        "logs": false,
        "hasScannerContext": true,
        "organization": "exasol",
        "warningCount": 1,
        "warnings": []
    }
}
```
