### ISSUE TITLE
Evaluate Migration of RD Release Guide

### ISSUE THREAD

**Issue by ckunki** [exasol/project-keeper#544]
PK 4.2.0 introduces automated releases and hence may replace [Release Droid](https://github.com/exasol/release-droid/blob/main/doc/user_guide/user_guide.md#release-guide). However, RD feature "Release Guide" has not been reimplemented yet. 

The current ticket requests to review re-evaluate this feature 
* Can it be reimplemented with PK? 
* Do we want to reimplement it? 
* Are there changes / adaption required as PK compared to RD uses a different Approach with GitHub workflows etc.?
* Idea: implement in GHA, see https://github.com/exasol/github-issue-adapter/issues/248

**Comment by kaklakariada** [comment]
Implemented in a different project.
